// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Plainion.JekyllLint")>]
[<assembly: AssemblyProductAttribute("Plainion.JekyllLint")>]
[<assembly: AssemblyDescriptionAttribute("Plainion.JekyllLint")>]
[<assembly: AssemblyCopyrightAttribute("Copyright @ 2019")>]
[<assembly: AssemblyVersionAttribute("2.0")>]
[<assembly: AssemblyFileVersionAttribute("2.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Plainion.JekyllLint"
    let [<Literal>] AssemblyProduct = "Plainion.JekyllLint"
    let [<Literal>] AssemblyDescription = "Plainion.JekyllLint"
    let [<Literal>] AssemblyCopyright = "Copyright @ 2019"
    let [<Literal>] AssemblyVersion = "2.0"
    let [<Literal>] AssemblyFileVersion = "2.0"
