// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Plainion.JekyllLint.Specs")>]
[<assembly: AssemblyProductAttribute("Plainion.JekyllLint")>]
[<assembly: AssemblyDescriptionAttribute("Plainion.JekyllLint")>]
[<assembly: AssemblyCopyrightAttribute("Copyright @ 2021")>]
[<assembly: AssemblyVersionAttribute("2.1")>]
[<assembly: AssemblyFileVersionAttribute("2.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Plainion.JekyllLint.Specs"
    let [<Literal>] AssemblyProduct = "Plainion.JekyllLint"
    let [<Literal>] AssemblyDescription = "Plainion.JekyllLint"
    let [<Literal>] AssemblyCopyright = "Copyright @ 2021"
    let [<Literal>] AssemblyVersion = "2.1"
    let [<Literal>] AssemblyFileVersion = "2.1"
