// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Plainion.JekyllLint.Specs")>]
[<assembly: AssemblyProductAttribute("Plainion.JekyllLint")>]
[<assembly: AssemblyDescriptionAttribute("Plainion.JekyllLint")>]
[<assembly: AssemblyCopyrightAttribute("Copyright @ 2018")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Plainion.JekyllLint.Specs"
    let [<Literal>] AssemblyProduct = "Plainion.JekyllLint"
    let [<Literal>] AssemblyDescription = "Plainion.JekyllLint"
    let [<Literal>] AssemblyCopyright = "Copyright @ 2018"
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
